# config context path to "/" by setting an empty string
#server:
#  contextPath:
server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
logging:
  level:
    root: debug